site_name: Lei de Avaliação Neuropsicológica no SUS
site_description: Projeto legislativo colaborativo
site_author: Comunidade

repo_url: https://github.com/goldenluke/pl-neuropsicologia-sus
repo_name: Editar no GitHub
edit_uri: edit/main/

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - content.action.edit
    - content.action.view
    - search.suggest
    - search.highlight


extra_css:
  - stylesheets/abnt.css

nav:
  - Início: index.md
  - Exposição de Motivos: docs/exposicao-motivos.md
  - Fundamentação Teórica: docs/fundamentacao-teorica.md
  - Direito Comparado: docs/direito-comparado.md

  - Projeto de Lei:
      - Artigo 1: projeto-lei/artigo-1.md
      - Artigo 2: projeto-lei/artigo-2.md
      - Artigo 3: projeto-lei/artigo-3.md
      - Artigo 4: projeto-lei/artigo-4.md
      - Artigo 5: projeto-lei/artigo-5.md
      - Artigo 6: projeto-lei/artigo-6.md
      - Artigo 7: projeto-lei/artigo-7.md
      - Artigo 8: projeto-lei/artigo-8.md
      - Artigo 9: projeto-lei/artigo-9.md
      - Artigo 10: projeto-lei/artigo-10.md

  - Discussão:
      - Debate Técnico: discussao/debate-tecnico.md
      - Propostas de Emenda: discussao/propostas-emenda.md
